version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  pre_build:
      commands:
        - echo Pre-build phase completed!
  build:
      commands:
        - echo Running build
      
  post_build:
    commands:
      - echo Build completed successfully!

artifacts:
  files:
    - '**/*'
  base-directory: .
